# Generated by Django 6.0.6 on 2026-06-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255, unique=True)),
                ('site', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('extracted_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
